---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: dact-os
description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 43

modules:
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
