---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: dact-os
description: This is my personal OS image.
base-image: quay.io/fedora-ostree-desktops/silverblue
image-version: 43

modules:
  - type: signing
  - type: dnf
    install:
      packages:
        - input-remapper
        - libappindicator-gtk3 # dependency for AppIndicator extension
  - type: dnf
    repos:
      cleanup: true
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    install:
      - brave-browser
  - type: dnf
    remove:
      packages:
        - fedora-flathub-remote
        - fedora-third-party
        - gnome-software
        - gnome-software-rpm-ostree
        - gnome-tour
        - gnome-system-monitor
        - yelp
        - gnome-shell-extension-common
        - gnome-shell-extension-apps-menu
        - gnome-shell-extension-launch-new-instance
        - gnome-shell-extension-places-menu
        - gnome-shell-extension-window-list
        - gnome-shell-extension-background-logo
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - io.github.kolunmi.Bazaar
  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
  - type: systemd
    system:
      enabled:
        - input-remapper.service
      masked:
        - rpm-ostreed-automatic.timer
        - flatpak-add-fedora-repos.service
